name: Generacion y publicacion de .deb

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Eliminar tags previos
        run: |
          gh release list --limit 100 | awk '{print $1}' | xargs -I {} gh release delete {} --yes || true
          git tag | xargs -I {} git push --delete origin {} || true
          git tag | xargs -I {} git tag -d {} || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Establecer dependencias
        run: |
          sudo apt update
          sudo apt install -y dpkg-dev

      - name: Contruccion .deb
        run: |
          chmod 0755 DEBIAN/*
          chmod +x usr/sbin/victrix
          cd ..
          dpkg-deb --build victrix victrix_1.0_all.deb
          mv victrix_1.0_all.deb victrix/victrix.deb

      - name: Crear publicacion y subida de .deb
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: ${{ github.run_number }}
          draft: false
          prerelease: false
          files: victrix.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}